const DEFAULT_REVEAL_DELAY = 0;
const DEFAULT_REVEAL_BOTTOM_ROOT_MARGIN = "-10%";

const REVEAL_THRESHOLD = 0.15;

export {
  DEFAULT_REVEAL_DELAY,
  DEFAULT_REVEAL_BOTTOM_ROOT_MARGIN,
  REVEAL_THRESHOLD,
};
